CREATE TABLE IF NOT EXISTS wallets (
    ID varchar(255) PRIMARY KEY,
    CREATED_AT timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELETED boolean NOT NULL DEFAULT false,
    VERSION int,
    ADDRESS varchar(255),
    WALLET_TYPE int,
    CHAIN int
);

CREATE UNIQUE INDEX IF NOT EXISTS wallet_address_idx on wallets (ADDRESS,CHAIN);

ALTER TABLE tokens ADD COLUMN IF NOT EXISTS OWNER_USER_ID varchar(255);
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS OWNER_ADDRESSES varchar(255) [];
ALTER TABLE tokens ALTER COLUMN CHAIN TYPE int;
ALTER TABLE tokens DROP COLUMN IF EXISTS OWNER_ADDRESS;

CREATE UNIQUE INDEX IF NOT EXISTS token_id_contract_address_owner_user_id_idx ON tokens (TOKEN_ID, CONTRACT_ADDRESS, OWNER_USER_ID);

CREATE INDEX IF NOT EXISTS token_id_contract_address_idx ON tokens (TOKEN_ID, CONTRACT_ADDRESS);

CREATE INDEX IF NOT EXISTS owner_user_id_idx ON tokens (OWNER_USER_ID);

CREATE INDEX IF NOT EXISTS token_contract_address_idx ON tokens (CONTRACT_ADDRESS);

CREATE INDEX IF NOT EXISTS block_number_idx ON tokens (BLOCK_NUMBER);

ALTER TABLE contracts ADD COLUMN IF NOT EXISTS CHAIN int;

CREATE UNIQUE INDEX IF NOT EXISTS contract_address_idx ON contracts (ADDRESS,CHAIN);

