SET SCHEMA 'public';

CREATE TABLE IF NOT EXISTS events (
    ID varchar(255) PRIMARY KEY,
    USER_ID varchar(255),
    VERSION int,
    EVENT_TYPE varchar(255),
    CREATED_AT timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MESSAGE jsonb
);

CREATE INDEX IF NOT EXISTS user_id_event_type_created_at ON events (USER_ID, EVENT_TYPE, CREATED_AT);
