CREATE TABLE IF NOT EXISTS follows (
    ID varchar(255) PRIMARY KEY,
    FOLLOWER varchar(255) NOT NULL,
    FOLLOWEE varchar(255) NOT NULL,
    DELETED bool,
    CREATED_AT timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (FOLLOWER, FOLLOWEE)
);
