FROM postgres:14

RUN apt-get update
RUN apt-get -y install postgresql-14-cron

ENV POSTGRES_HOST_AUTH_METHOD trust
ENV POSTGRES_USER postgres
ENV POSTGRES_DB postgres
ARG PGHOST="localhost"
ARG PGPORT=5432
ARG PGUSER=postgres
ARG PGPASSWORD=""
ARG PGDATABASE=postgres
ARG PGTESTUSER=benny
ARG PGDATABASE=postgres
COPY 01_init.sql /docker-entrypoint-initdb.d/01_init.sql
COPY postgres.conf /etc/postgresql/postgresql.conf
