# Proxies Cloud SQL connections using local "gcloud auth" credentials so we
# don't have to allowlist IPs or use SSL certificates when connecting.

# Prod DB:         127.0.0.1:6543
# Dev DB:          127.0.0.1:6643

version: "3.9"
services:
  cloud-sql-proxy-prod:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy
    ports:
      - "6543:6543"
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/config
    command: >
      --address=0.0.0.0 --credentials-file=/config
      '${SQL_CONNECTION_NAME_PROD_DB}?port=6543'

  cloud-sql-proxy-dev:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy
    ports:
      - "6643:6643"
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/config
    command: >
      --address=0.0.0.0 --credentials-file=/config
      '${SQL_CONNECTION_NAME_DEV_DB}?port=6643'
