// Code generated by github.com/vektah/dataloaden, DO NOT EDIT.

package dataloader

import (
	"sync"
	"time"

	"github.com/mikeydub/go-gallery/service/persist"
)

// CollectionsLoaderConfig captures the config to create a new CollectionsLoader
type CollectionsLoaderConfig struct {
	// Fetch is a method that provides the data for the loader
	Fetch func(keys []string) ([][]persist.Collection, []error)

	// Wait is how long wait before sending a batch
	Wait time.Duration

	// MaxBatch will limit the maximum number of keys to send in one batch, 0 = not limit
	MaxBatch int
}

// NewCollectionsLoader creates a new CollectionsLoader given a fetch, wait, and maxBatch
func NewCollectionsLoader(config CollectionsLoaderConfig) *CollectionsLoader {
	return &CollectionsLoader{
		fetch:    config.Fetch,
		wait:     config.Wait,
		maxBatch: config.MaxBatch,
	}
}

// CollectionsLoader batches and caches requests
type CollectionsLoader struct {
	// this method provides the data for the loader
	fetch func(keys []string) ([][]persist.Collection, []error)

	// how long to done before sending a batch
	wait time.Duration

	// this will limit the maximum number of keys to send in one batch, 0 = no limit
	maxBatch int

	// INTERNAL

	// lazily created cache
	cache map[string][]persist.Collection

	// the current batch. keys will continue to be collected until timeout is hit,
	// then everything will be sent to the fetch method and out to the listeners
	batch *collectionsLoaderBatch

	// mutex to prevent races
	mu sync.Mutex
}

type collectionsLoaderBatch struct {
	keys    []string
	data    [][]persist.Collection
	error   []error
	closing bool
	done    chan struct{}
}

// Load a Collection by key, batching and caching will be applied automatically
func (l *CollectionsLoader) Load(key string) ([]persist.Collection, error) {
	return l.LoadThunk(key)()
}

// LoadThunk returns a function that when called will block waiting for a Collection.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *CollectionsLoader) LoadThunk(key string) func() ([]persist.Collection, error) {
	l.mu.Lock()
	if it, ok := l.cache[key]; ok {
		l.mu.Unlock()
		return func() ([]persist.Collection, error) {
			return it, nil
		}
	}
	if l.batch == nil {
		l.batch = &collectionsLoaderBatch{done: make(chan struct{})}
	}
	batch := l.batch
	pos := batch.keyIndex(l, key)
	l.mu.Unlock()

	return func() ([]persist.Collection, error) {
		<-batch.done

		var data []persist.Collection
		if pos < len(batch.data) {
			data = batch.data[pos]
		}

		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		if err == nil {
			l.mu.Lock()
			l.unsafeSet(key, data)
			l.mu.Unlock()
		}

		return data, err
	}
}

// LoadAll fetches many keys at once. It will be broken into appropriate sized
// sub batches depending on how the loader is configured
func (l *CollectionsLoader) LoadAll(keys []string) ([][]persist.Collection, []error) {
	results := make([]func() ([]persist.Collection, error), len(keys))

	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}

	collections := make([][]persist.Collection, len(keys))
	errors := make([]error, len(keys))
	for i, thunk := range results {
		collections[i], errors[i] = thunk()
	}
	return collections, errors
}

// LoadAllThunk returns a function that when called will block waiting for a Collections.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *CollectionsLoader) LoadAllThunk(keys []string) func() ([][]persist.Collection, []error) {
	results := make([]func() ([]persist.Collection, error), len(keys))
	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}
	return func() ([][]persist.Collection, []error) {
		collections := make([][]persist.Collection, len(keys))
		errors := make([]error, len(keys))
		for i, thunk := range results {
			collections[i], errors[i] = thunk()
		}
		return collections, errors
	}
}

// Prime the cache with the provided key and value. If the key already exists, no change is made
// and false is returned.
// (To forcefully prime the cache, clear the key first with loader.clear(key).prime(key, value).)
func (l *CollectionsLoader) Prime(key string, value []persist.Collection) bool {
	l.mu.Lock()
	var found bool
	if _, found = l.cache[key]; !found {
		// make a copy when writing to the cache, its easy to pass a pointer in from a loop var
		// and end up with the whole cache pointing to the same value.
		cpy := make([]persist.Collection, len(value))
		copy(cpy, value)
		l.unsafeSet(key, cpy)
	}
	l.mu.Unlock()
	return !found
}

// Clear the value at key from the cache, if it exists
func (l *CollectionsLoader) Clear(key string) {
	l.mu.Lock()
	delete(l.cache, key)
	l.mu.Unlock()
}

func (l *CollectionsLoader) unsafeSet(key string, value []persist.Collection) {
	if l.cache == nil {
		l.cache = map[string][]persist.Collection{}
	}
	l.cache[key] = value
}

// keyIndex will return the location of the key in the batch, if its not found
// it will add the key to the batch
func (b *collectionsLoaderBatch) keyIndex(l *CollectionsLoader, key string) int {
	for i, existingKey := range b.keys {
		if key == existingKey {
			return i
		}
	}

	pos := len(b.keys)
	b.keys = append(b.keys, key)
	if pos == 0 {
		go b.startTimer(l)
	}

	if l.maxBatch != 0 && pos >= l.maxBatch-1 {
		if !b.closing {
			b.closing = true
			l.batch = nil
			go b.end(l)
		}
	}

	return pos
}

func (b *collectionsLoaderBatch) startTimer(l *CollectionsLoader) {
	time.Sleep(l.wait)
	l.mu.Lock()

	// we must have hit a batch limit and are already finalizing this batch
	if b.closing {
		l.mu.Unlock()
		return
	}

	l.batch = nil
	l.mu.Unlock()

	b.end(l)
}

func (b *collectionsLoaderBatch) end(l *CollectionsLoader) {
	b.data, b.error = l.fetch(b.keys)
	close(b.done)
}
