// Code generated by github.com/vektah/dataloaden, DO NOT EDIT.

package dataloader

import (
	"sync"
	"time"

<<<<<<< HEAD
	"github.com/mikeydub/go-gallery/db/gen/coredb"
=======
	"github.com/mikeydub/go-gallery/db/sqlc/coregen"
>>>>>>> 93a3a41 (Add indexer models)
	"github.com/mikeydub/go-gallery/service/persist"
)

// TokenLoaderByIDConfig captures the config to create a new TokenLoaderByID
type TokenLoaderByIDConfig struct {
	// Fetch is a method that provides the data for the loader
<<<<<<< HEAD
	Fetch func(keys []persist.DBID) ([]coredb.Token, []error)
=======
	Fetch func(keys []persist.DBID) ([]coregen.Token, []error)
>>>>>>> 93a3a41 (Add indexer models)

	// Wait is how long wait before sending a batch
	Wait time.Duration

	// MaxBatch will limit the maximum number of keys to send in one batch, 0 = not limit
	MaxBatch int
}

// NewTokenLoaderByID creates a new TokenLoaderByID given a fetch, wait, and maxBatch
func NewTokenLoaderByID(config TokenLoaderByIDConfig) *TokenLoaderByID {
	return &TokenLoaderByID{
		fetch:    config.Fetch,
		wait:     config.Wait,
		maxBatch: config.MaxBatch,
	}
}

// TokenLoaderByID batches and caches requests
type TokenLoaderByID struct {
	// this method provides the data for the loader
<<<<<<< HEAD
	fetch func(keys []persist.DBID) ([]coredb.Token, []error)
=======
	fetch func(keys []persist.DBID) ([]coregen.Token, []error)
>>>>>>> 93a3a41 (Add indexer models)

	// how long to done before sending a batch
	wait time.Duration

	// this will limit the maximum number of keys to send in one batch, 0 = no limit
	maxBatch int

	// INTERNAL

	// lazily created cache
<<<<<<< HEAD
	cache map[persist.DBID]coredb.Token
=======
	cache map[persist.DBID]coregen.Token
>>>>>>> 93a3a41 (Add indexer models)

	// the current batch. keys will continue to be collected until timeout is hit,
	// then everything will be sent to the fetch method and out to the listeners
	batch *tokenLoaderByIDBatch

	// mutex to prevent races
	mu sync.Mutex
}

type tokenLoaderByIDBatch struct {
	keys    []persist.DBID
<<<<<<< HEAD
	data    []coredb.Token
=======
	data    []coregen.Token
>>>>>>> 93a3a41 (Add indexer models)
	error   []error
	closing bool
	done    chan struct{}
}

// Load a Token by key, batching and caching will be applied automatically
<<<<<<< HEAD
func (l *TokenLoaderByID) Load(key persist.DBID) (coredb.Token, error) {
=======
func (l *TokenLoaderByID) Load(key persist.DBID) (coregen.Token, error) {
>>>>>>> 93a3a41 (Add indexer models)
	return l.LoadThunk(key)()
}

// LoadThunk returns a function that when called will block waiting for a Token.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
<<<<<<< HEAD
func (l *TokenLoaderByID) LoadThunk(key persist.DBID) func() (coredb.Token, error) {
	l.mu.Lock()
	if it, ok := l.cache[key]; ok {
		l.mu.Unlock()
		return func() (coredb.Token, error) {
=======
func (l *TokenLoaderByID) LoadThunk(key persist.DBID) func() (coregen.Token, error) {
	l.mu.Lock()
	if it, ok := l.cache[key]; ok {
		l.mu.Unlock()
		return func() (coregen.Token, error) {
>>>>>>> 93a3a41 (Add indexer models)
			return it, nil
		}
	}
	if l.batch == nil {
		l.batch = &tokenLoaderByIDBatch{done: make(chan struct{})}
	}
	batch := l.batch
	pos := batch.keyIndex(l, key)
	l.mu.Unlock()

<<<<<<< HEAD
	return func() (coredb.Token, error) {
		<-batch.done

		var data coredb.Token
=======
	return func() (coregen.Token, error) {
		<-batch.done

		var data coregen.Token
>>>>>>> 93a3a41 (Add indexer models)
		if pos < len(batch.data) {
			data = batch.data[pos]
		}

		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		if err == nil {
			l.mu.Lock()
			l.unsafeSet(key, data)
			l.mu.Unlock()
		}

		return data, err
	}
}

// LoadAll fetches many keys at once. It will be broken into appropriate sized
// sub batches depending on how the loader is configured
<<<<<<< HEAD
func (l *TokenLoaderByID) LoadAll(keys []persist.DBID) ([]coredb.Token, []error) {
	results := make([]func() (coredb.Token, error), len(keys))
=======
func (l *TokenLoaderByID) LoadAll(keys []persist.DBID) ([]coregen.Token, []error) {
	results := make([]func() (coregen.Token, error), len(keys))
>>>>>>> 93a3a41 (Add indexer models)

	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}

<<<<<<< HEAD
	tokens := make([]coredb.Token, len(keys))
=======
	tokens := make([]coregen.Token, len(keys))
>>>>>>> 93a3a41 (Add indexer models)
	errors := make([]error, len(keys))
	for i, thunk := range results {
		tokens[i], errors[i] = thunk()
	}
	return tokens, errors
}

// LoadAllThunk returns a function that when called will block waiting for a Tokens.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
<<<<<<< HEAD
func (l *TokenLoaderByID) LoadAllThunk(keys []persist.DBID) func() ([]coredb.Token, []error) {
	results := make([]func() (coredb.Token, error), len(keys))
	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}
	return func() ([]coredb.Token, []error) {
		tokens := make([]coredb.Token, len(keys))
=======
func (l *TokenLoaderByID) LoadAllThunk(keys []persist.DBID) func() ([]coregen.Token, []error) {
	results := make([]func() (coregen.Token, error), len(keys))
	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}
	return func() ([]coregen.Token, []error) {
		tokens := make([]coregen.Token, len(keys))
>>>>>>> 93a3a41 (Add indexer models)
		errors := make([]error, len(keys))
		for i, thunk := range results {
			tokens[i], errors[i] = thunk()
		}
		return tokens, errors
	}
}

// Prime the cache with the provided key and value. If the key already exists, no change is made
// and false is returned.
// (To forcefully prime the cache, clear the key first with loader.clear(key).prime(key, value).)
<<<<<<< HEAD
func (l *TokenLoaderByID) Prime(key persist.DBID, value coredb.Token) bool {
=======
func (l *TokenLoaderByID) Prime(key persist.DBID, value coregen.Token) bool {
>>>>>>> 93a3a41 (Add indexer models)
	l.mu.Lock()
	var found bool
	if _, found = l.cache[key]; !found {
		l.unsafeSet(key, value)
	}
	l.mu.Unlock()
	return !found
}

// Clear the value at key from the cache, if it exists
func (l *TokenLoaderByID) Clear(key persist.DBID) {
	l.mu.Lock()
	delete(l.cache, key)
	l.mu.Unlock()
}

<<<<<<< HEAD
func (l *TokenLoaderByID) unsafeSet(key persist.DBID, value coredb.Token) {
	if l.cache == nil {
		l.cache = map[persist.DBID]coredb.Token{}
=======
func (l *TokenLoaderByID) unsafeSet(key persist.DBID, value coregen.Token) {
	if l.cache == nil {
		l.cache = map[persist.DBID]coregen.Token{}
>>>>>>> 93a3a41 (Add indexer models)
	}
	l.cache[key] = value
}

// keyIndex will return the location of the key in the batch, if its not found
// it will add the key to the batch
func (b *tokenLoaderByIDBatch) keyIndex(l *TokenLoaderByID, key persist.DBID) int {
	for i, existingKey := range b.keys {
		if key == existingKey {
			return i
		}
	}

	pos := len(b.keys)
	b.keys = append(b.keys, key)
	if pos == 0 {
		go b.startTimer(l)
	}

	if l.maxBatch != 0 && pos >= l.maxBatch-1 {
		if !b.closing {
			b.closing = true
			l.batch = nil
			go b.end(l)
		}
	}

	return pos
}

func (b *tokenLoaderByIDBatch) startTimer(l *TokenLoaderByID) {
	time.Sleep(l.wait)
	l.mu.Lock()

	// we must have hit a batch limit and are already finalizing this batch
	if b.closing {
		l.mu.Unlock()
		return
	}

	l.batch = nil
	l.mu.Unlock()

	b.end(l)
}

func (b *tokenLoaderByIDBatch) end(l *TokenLoaderByID) {
	b.data, b.error = l.fetch(b.keys)
	close(b.done)
}
