version: 2.1
workflows:
  main:
    jobs:
      - build
      - integration-tests
      - unit-tests:
          requires:
            - build
      - deploy:
          filters:
            branches:
              only:
                - "main"
      - post-deploy:
          requires:
            - deploy
jobs:
  build:
    working_directory: ~/go-gallery
    docker:
      - image: cimg/go:1.16
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v5-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v5-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  # using a machine executor to run docker, which in turn installs postgres + redis and runs underlying tests
  # https://circleci.com/docs/2.0/executor-types/#using-machine
  unit-tests:
    working_directory: ~/go-gallery
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: false # can enable when on performance plan
    environment:
      GO_VERSION: 1.16.13
      GOTESTSUM_VERSION: 1.7.0
    steps:
      - checkout
      - run:
          name: Install Go
          command: |
            mkdir -p ~/bin ~/go
            curl -L --output - https://go.dev/dl/go$GO_VERSION.linux-amd64.tar.gz | tar xz -C ~/bin
            echo 'export GOROOT=~/bin/go' >> $BASH_ENV
            echo 'export GOPATH=~/go' >> $BASH_ENV
            echo 'export PATH=$GOROOT/bin:$GOPATH/bin:$PATH' >> $BASH_ENV
      - restore_cache:
          keys:
            - go-mod-v5-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: |
            go mod download
            go get gotest.tools/gotestsum@v$GOTESTSUM_VERSION
      - save_cache:
          key: go-mod-v5-{{ checksum "go.sum" }}
          paths:
            - "~/go/pkg/mod"
      - run:
          name: "Update apt"
          command: sudo apt-get update
      - run:
          name: "Install Keybase"
          command: |
            curl --remote-name https://prerelease.keybase.io/keybase_amd64.deb
            sudo apt install ./keybase_amd64.deb
            run_keybase -g
      - run:
          name: "Oneshot Keybase"
          command: "keybase oneshot"
      - run:
          name: "Decrypt secrets"
          command: keybase decrypt -i _encrypted_local -o _local.zip
      - run:
          name: "Decrypt deploy"
          command: keybase decrypt -i _encrypted_deploy -o _deploy.zip
      - run:
          name: "Install cli dependencies"
          command: sudo apt-get -y install unzip
      - run:
          name: "Unzip secrets file"
          command: echo "A" | unzip _local.zip -d _local
      - run:
          name: "Unzip deploy file"
          command: echo "A" | unzip _deploy.zip -d _deploy
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml -- -short ./...
      - store_test_results:
          path: /tmp/test-reports
  integration-tests:
    working_directory: ~/go-gallery
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: false # can enable when on performance plan
    environment:
      GO_VERSION: 1.16.13
      GOTESTSUM_VERSION: 1.7.0
    steps:
      - checkout
      - run:
          name: Install Go
          command: |
            mkdir -p ~/bin ~/go
            curl -L --output - https://go.dev/dl/go$GO_VERSION.linux-amd64.tar.gz | tar xz -C ~/bin
            echo 'export GOROOT=~/bin/go' >> $BASH_ENV
            echo 'export GOPATH=~/go' >> $BASH_ENV
            echo 'export PATH=$GOROOT/bin:$GOPATH/bin:$PATH' >> $BASH_ENV
      - restore_cache:
          keys:
            - go-mod-v1-usr-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: |
            go mod download
            go get gotest.tools/gotestsum@v$GOTESTSUM_VERSION
      - save_cache:
          key: go-mod-v1-usr-{{ checksum "go.sum" }}
          paths:
            - "~/go/pkg/mod"
      - run:
          name: "Update apt"
          command: sudo apt-get update
      - run:
          name: "Install Keybase"
          command: |
            curl --remote-name https://prerelease.keybase.io/keybase_amd64.deb
            sudo apt install ./keybase_amd64.deb
            run_keybase -g
      - run:
          name: "Oneshot Keybase"
          command: "keybase oneshot"
      - run:
          name: "Decrypt secrets"
          command: keybase decrypt -i _encrypted_local -o _local.zip
      - run:
          name: "Decrypt deploy"
          command: keybase decrypt -i _encrypted_deploy -o _deploy.zip
      - run:
          name: "Install cli dependencies"
          command: sudo apt-get -y install unzip
      - run:
          name: "Unzip secrets file"
          command: echo "A" | unzip _local.zip -d _local
      - run:
          name: "Unzip deploy file"
          command: echo "A" | unzip _deploy.zip -d _deploy
      - run:
          name: Run backend integration-tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/integration-tests.xml -- -run TestIntegrationTest ./server/... -args -chain ethereum -chainID 1
      - run:
          name: Run indexer integration-tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/indexer-integration-tests.xml -- ./indexer/...
      - store_test_results:
          path: /tmp/test-reports
  deploy:
    working_directory: ~/go-gallery
    docker:
      - image: keybaseio/client
    environment:
      - SENTRY_ORG: usegallery
      - SENTRY_PROJECT: gallery-backend
    steps:
      - checkout
      - run:
          name: "Oneshot Keybase"
          command: "keybase oneshot"
      - run:
          name: "Decrypt secrets"
          command: keybase decrypt -i _encrypted_deploy -o _deploy.zip
      - run:
          name: "Update apt"
          command: apt-get update
      - run:
          name: "Install cli dependencies"
          command: apt-get -y install unzip curl sudo python3 make git
      - run:
          name: "Install Sentry"
          command: curl -sL https://sentry.io/get-cli/ | bash
      - run:
          name: "Unzip secrets file"
          command: unzip _deploy.zip -d _deploy
      - run:
          command: |
            install () {
              # Set sudo to work whether logged in as root user or non-root user
              if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
              cd ~/
              curl -Ss --retry 5 https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-353.0.0-linux-x86_64.tar.gz | tar xz
              echo 'source ~/google-cloud-sdk/path.bash.inc' >> $BASH_ENV
            }

            if grep 'docker\|lxc' /proc/1/cgroup > /dev/null 2>&1; then
              if [[ $(command -v gcloud) == "" ]]; then
                install
              else
                echo "gcloud CLI is already installed."
              fi
            else
              echo "----------------------------------------------------------------------------------------------------"
              echo "this is a machine executor job, replacing default installation of gcloud CLI"
              echo "----------------------------------------------------------------------------------------------------"
              sudo rm -rf /opt/google-cloud-sdk
              install
            fi
          name: Install latest gcloud CLI version, if not available
      - run:
          command: |
            # Store service account
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json

            # Initialize gcloud CLI
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID

            if [[ -n $GOOGLE_COMPUTE_ZONE ]]; then
              gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
            elif [[ -n $GOOGLE_COMPUTE_REGION ]]; then
              gcloud --quiet config set compute/region $GOOGLE_COMPUTE_REGION
            else
              echo "ERROR: Set GOOGLE_COMPUTE_ZONE or GOOGLE_COMPUTE_REGION env variable" >&2
              exit 1
            fi
          name: Initialize gcloud CLI to connect to Google Cloud
      - run:
          name: "Deploy Backend"
          command: |
            cd _deploy
            make deploy-dev-backend
  post-deploy:
    working_directory: ~/go-gallery
    docker:
      - image: cimg/base:stable
    environment:
      - HEALTH_URL: https://api.dev.gallery.so/glry/v1/health
      - GRACE: 20
      - TIMES: 8
      - INTERVAL: 10
    steps:
      - run:
          name: "Ping Backend"
          command: |
            echo "-------------------------------"
            echo " INFO: letting backend startup "
            echo "-------------------------------"
            sleep $GRACE

            for ((i=0; i<$TIMES; i++)); do
            if [[ -z $(curl -XGET -Is $HEALTH_URL | head -n1 | grep 200) ]]; then
              echo "-------------------------------"
              echo " INFO: [attempt $i] waiting... "
              echo "-------------------------------"
              sleep $INTERVAL
            else
              echo "-------------------------------"
              echo " INFO: backend is operational! "
              echo "-------------------------------"
              exit 0
            fi
            done

            echo "-------------------------------"
            echo " ERROR: failed to hit backend! "
            echo "-------------------------------"
            exit 1
