version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.2.0
workflows:
  main:
    jobs:
      - build
      - gcp-cli/install_and_initialize_cli
      - keybase:
          requires:
            - gcp-cli/install_and_initialize_cli
          # filters:
          #   branches:
          #     only:
          #       - "main"
jobs:
  build:
    working_directory: ~/go-gallery
    docker:
      - image: circleci/golang:1.15.8
      - image: mongo:latest
      - image: redis:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports
  keybase:
    working_directory: ~/go-gallery
    docker:
      - image: keybaseio/client
    steps:
      - checkout
      - run:
          name: "Login keybase"
          command: "keybase login gallerycibot --paperkey $KEYBASE_PAPERKEY"
      - run:
          name: "Decrypt secrets"
          command: "keybase decrypt -i secrits -o decrypted.zip"
      - run:
          name: "Unzip secrets file"
          command: "unzip decrypted.zip"
      - run:
          name: "Copy app.yamls"
          command: "cp -R decrypted/* ./"
      - run:
          name: "Deploy gcp"
          command: "gcloud app deploy"