# syntax=docker/dockerfile:1

FROM golang:1.16-buster

RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Install deps
WORKDIR /app
COPY go.mod go.sum /app/
RUN go mod download

COPY . /app
RUN go build -o ./bin/mediaprocessing ./cmd/mediaprocessing/main.go

EXPOSE 6500
USER nobody
ENTRYPOINT ["./bin/mediaprocessing"]