/* {% require_sudo %} */
ALTER TABLE user_events ADD COLUMN IF NOT EXISTS SENT bool DEFAULT NULL;
ALTER TABLE nft_events ADD COLUMN IF NOT EXISTS SENT bool DEFAULT NULL;
ALTER TABLE collection_events ADD COLUMN IF NOT EXISTS SENT bool DEFAULT NULL;
