/* {% require_sudo %} */
ALTER TABLE follows ADD COLUMN IF NOT EXISTS CREATED_AT timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE follows ADD COLUMN IF NOT EXISTS LAST_UPDATED timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS follows_follower_last_updated_idx ON follows (FOLLOWER, LAST_UPDATED DESC);
CREATE INDEX IF NOT EXISTS follows_followee_last_updated_idx ON follows (FOLLOWEE, LAST_UPDATED DESC);
