/* {% require_sudo %} */
CREATE TABLE IF NOT EXISTS admires(
    ID varchar(255) PRIMARY KEY,
    VERSION int NOT NULL DEFAULT 0,
    FEED_EVENT_ID varchar(255) NOT NULL REFERENCES feed_events (ID),
    ACTOR_ID varchar(255) NOT NULL REFERENCES users (ID),
    DELETED boolean NOT NULL DEFAULT false,
    CREATED_AT timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS admire_actor_feed_event_idx ON admires (ACTOR_ID, FEED_EVENT_ID) WHERE DELETED = false;

CREATE INDEX IF NOT EXISTS admire_feed_event_idx ON admires (FEED_EVENT_ID);

CREATE TABLE IF NOT EXISTS comments(
    ID varchar(255) PRIMARY KEY,
    VERSION int NOT NULL DEFAULT 0,
    FEED_EVENT_ID varchar(255) NOT NULL REFERENCES feed_events (ID),
    ACTOR_ID varchar(255) NOT NULL REFERENCES users (ID),
	REPLY_TO varchar(255) REFERENCES comments (ID),
	COMMENT varchar NOT NULL,
    DELETED boolean NOT NULL DEFAULT false,
    CREATED_AT timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS comment_feed_event_idx ON comments (FEED_EVENT_ID);
