package glry_db

import (
	"context"
	"time"

	"github.com/mikeydub/go-gallery/glry_core"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo/options"
	// "github.com/davecgh/go-spew/spew"
)

//-------------------------------------------------------------

const nftColName = "glry_nfts"

type GLRYnftID string
type GLRYnft struct {
	VersionInt    int64     `bson:"version"              json:"version"` // schema version for this model
	IDstr         GLRYnftID `bson:"_id"                  json:"id"`
	CreationTimeF float64   `bson:"creation_time"        json:"creation_time"`
	DeletedBool   bool      `bson:"deleted"`

	NameStr           string `bson:"name,omitempty"                 json:"name"`
	DescriptionStr    string `bson:"description,omitempty"          json:"description"`
	CollectorsNoteStr string `bson:"collectors_note,omitempty" json:"collectors_note"`

	ExternalURLstr      string       `bson:"external_url,omitempty"         json:"external_url"`
	TokenMetadataUrlStr string       `bson:"token_metadata_url,omitempty" json:"token_metadata_url"`
	CreatorAddressStr   string       `bson:"creator_address,omitempty"      json:"creator_address"`
	CreatorNameStr      string       `bson:"creator_name,omitempty" json:"creator_name"`
	OwnerAddressStr     string       `bson:"owner_address,omitempty" json:"owner_address"`
	Contract            GLRYcontract `bson:"contract,omitempty"     json:"contract"`

	// OPEN_SEA_TOKEN_ID
	// https://api.opensea.io/api/v1/asset/0xa7d8d9ef8d8ce8992df33d8b8cf4aebabd5bd270/26000331
	// (/asset/:contract_address/:token_id)
	OpenSeaIDstr   string `bson:"opensea_id,omitempty"       json:"opensea_id"`
	OpenSeaTokenID string `bson:"opensea_token_id,omitempty" json:"opensea_token_id"`

	// IMAGES - OPENSEA
	ImageURLstr             string `bson:"image_url,omitempty"           json:"image_url"`
	ImageThumbnailURLstr    string `bson:"image_thumbnail_url,omitempty" json:"image_thumbnail_url"`
	ImagePreviewURLstr      string `bson:"image_preview_url,omitempty"   json:"image_preview_url"`
	ImageOriginalUrlStr     string `bson:"image_original_url,omitempty" json:"image_original_url"`
	AnimationUrlStr         string `bson:"animation_url,omitempty" json:"animation_url"`
	AnimationOriginalUrlStr string `bson:"animation_original_url,omitempty" json:"animation_original_url"`

	AcquisitionDateStr string `bson:"acquisition_date,omitempty" json:"acquisition_date"`
}

type GLRYcontract struct {
	ContractAddressStr      string `bson:"contract_address,omitempty"     json:"contract_address"`
	ContractNameStr         string `bson:"contract_name,omitempty" json:"contract_name"`
	ContractDescription     string `bson:"contract_description,omitempty" json:"contract_description"`
	ContractExternalLinkStr string `bson:"contract_external_link,omitempty" json:"contract_external_link"`
	ContractSchemaNameStr   string `bson:"contract_schema_name,omitempty" json:"contract_schema_name"`
	ContractSymbolStr       string `bson:"contract_symbol,omitempty" json:"contract_symbol"`
	ContractTotalSupplyInt  int    `bson:"contract_total_supply,omitempty" json:"contract_total_supply"`
}

/*// IS THIS REALLY NECESSARY? - why not just import directly from v0 DB into the v1 DB GLRYnft format?
// DEPRECATED!! - will be removed once we fully migrate to v1 server/db schema.
//                legacy NFT type, this is the schema in the initial v0 prototype of the system.
type GLRYnftLegacy struct {

	// ID - for now generated by the DB
	IDstr string `bson:"_id" json:"id"`

	// removed from newer NFT model, NFT's might be associated with multiple Users,
	// so we dont want to limit to a single user.
	UserIDstr string `bson:"user_id" json:"user_id"`

	ImageURLstr       string `bson:"image_url"           json:"image_url"`
	DescriptionStr    string `bson:"description"         json:"description"`
	NameStr           string `bson:"name"                json:"name"`
	CollectionNameStr string `bson:"collection_name"     json:"collection_name"`

	ExternalURLstr       string    `bson:"external_url"        json:"external_url"`
	CreatedDateF         float64   `bson:"created_date"        json:"created_date"`
	CreatorAddressStr    string    `bson:"creator_address"     json:"creator_address"`
	ContractAddressStr   string    `bson:"contract_address"    json:"contract_address"`
	TokenIDstr           int64     `bson:"token_id"            json:"token_id"`
	ImageThumbnailURLstr string    `bson:"image_thumbnail_url" json:"image_thumbnail_url"`
	ImagePreviewURLstr   string    `bson:"image_preview_url"   json:"image_preview_url"`

	PositionInt int64 `bson:"position" json:"position"`
	HiddenBool  bool  `bson:"hidden"   json:"hidden"`
}*/

//-------------------------------------------------------------
func NFTcreateBulk(pNFTlst []*GLRYnft,
	pCtx context.Context,
	pRuntime *glry_core.Runtime) error {

	mp := glry_core.NewMongoPersister(0, nftColName, pRuntime)

	return mp.InsertMany(pCtx, pNFTlst)
}

//-------------------------------------------------------------
func NFTcreate(pNFT *GLRYnft,
	pCtx context.Context,
	pRuntime *glry_core.Runtime) error {

	mp := glry_core.NewMongoPersister(0, nftColName, pRuntime)

	return mp.Insert(pCtx, pNFT)

}

//-------------------------------------------------------------
func NFTgetByUserID(pUserIDstr string,
	pCtx context.Context,
	pRuntime *glry_core.Runtime) ([]*GLRYnft, error) {
	opts := &options.FindOptions{}
	if deadline, ok := pCtx.Deadline(); ok {
		dur := time.Until(deadline)
		opts.MaxTime = &dur
	}
	mp := glry_core.NewMongoPersister(0, nftColName, pRuntime)
	result := []*GLRYnft{}

	if err := mp.Find(pCtx, bson.M{"user_id": pUserIDstr}, result, opts); err != nil {
		return nil, err
	}

	return nil, nil
}

//-------------------------------------------------------------

func NFTgetByID(pIDstr string, pCtx context.Context, pRuntime *glry_core.Runtime) ([]*GLRYnft, error) {

	opts := &options.FindOptions{}
	if deadline, ok := pCtx.Deadline(); ok {
		dur := time.Until(deadline)
		opts.MaxTime = &dur
	}

	mp := glry_core.NewMongoPersister(0, nftColName, pRuntime)
	result := []*GLRYnft{}

	if err := mp.Find(pCtx, bson.M{"_id": pIDstr}, result, opts); err != nil {
		return nil, err
	}

	return result, nil

}

//-------------------------------------------------------------

// NOTE: there is no gfcore mongo func for update... using default mongo lib for now
func NFTupdateById(pIDstr string, updatedNft *GLRYnft, pCtx context.Context, pRuntime *glry_core.Runtime) error {

	//------------------
	// VALIDATE
	if err := glry_core.Validate(updatedNft, pRuntime); err != nil {
		return err
	}

	mp := glry_core.NewMongoPersister(0, nftColName, pRuntime)

	return mp.Update(pCtx, bson.M{"_id": pIDstr}, updatedNft)

}
